---
apiVersion: v2
name: tsf-pipelines
description: TSF OpenShift Pipelines
type: application
version: "1.8.0"
appVersion: "1.20"
annotations:
  helmet.redhat-appstudio.github.com/product-name: OpenShift Pipelines
  helmet.redhat-appstudio.github.com/depends-on: tsf-openshift, tsf-subscriptions
  helmet.redhat-appstudio.github.com/integrations-required: tas
