---
{{- include "common.serviceAccount" . }}
---
{{- include "pipelines.TektonConfigRbac" . }}
---
{{- $namespaces := dict
  "notdefaultnamespace" .Values.pipelines.namespace
  "integrationsecretnamespace" .Values.pipelines.tsf.namespace
}}
{{- include "common.secretRWRoleBinding" (merge $namespaces .) }}
---
{{- include "common.clusterRoleBinding" . }}
