kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: tsf-tpa-integration
  namespace: {{ .Values.trustedProfileAnalyzer.integrationSecret.namespace }}
stringData:
  trustify_server_internal_url: https://server.{{ .Release.Namespace }}.svc.cluster.local
  trustify_server_external_url: https://server{{ .Values.trustedProfileAnalyzer.appDomain }}