---
apiVersion: v2
name: tsf-tas
description: Red Hat Trusted Artifact Signer
type: application
version: "1.8.0"
appVersion: "1.3"
annotations:
  helmet.redhat-appstudio.github.com/product-name: Trusted Artifact Signer
  helmet.redhat-appstudio.github.com/depends-on: tsf-openshift, tsf-subscriptions, tsf-infrastructure, tsf-iam
  helmet.redhat-appstudio.github.com/integrations-provided: tas
