---
apiVersion: v2
name: tsf-iam
description: TSF IAM
type: application
version: "1.8.0"
annotations:
  helmet.redhat-appstudio.github.com/depends-on: tsf-openshift, tsf-subscriptions, tsf-infrastructure
